apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app-pod
  labels:
    app: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: 123456789.dkr.ecr.us-east-1.amazonaws.com/rails-app:frggded
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
