apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app-pod
  labels:
    app: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: 177701659471.dkr.ecr.us-east-1.amazonaws.com/mdn-docker-repo:64b58bc
          env:
            - name: OTEL_SERVICE_NAME
              value: "blog-app-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              # Point to your OTel Collector Service
              value: "http://otel-daemonset-opentelemetry-collector.observability.svc:4318"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=default,deployment.environment=development"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
          resources:
            requests:
              cpu: "100m"      # Guaranteed 0.25 core
              memory: "256Mi"
            limits:
              cpu: "500m"      # Maximum 0.5 core
              memory: "512Mi"              
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
